classifier_path: "models/rybg/vit_supcon_model/classifier.pth"
encoder_path: "models/rybg/vit_supcon_model/encoder.pth"
model_config:
  vit_model:
      hidden_size: 768
      num_hidden_layers: 12
      num_attention_heads: 12
      intermediate_size: 3072
      hidden_act: "gelu"
      hidden_dropout_prob: 0.0
      attention_probs_dropout_prob: 0.0
      initializer_range: 0.02
      layer_norm_eps: 1.e-12
      image_size: 448
      patch_size: 16
      num_channels: 4
      qkv_bias: True
      decoder_num_attention_heads: 16
      decoder_hidden_size: 512
      decoder_num_hidden_layers: 8
      decoder_intermediate_size: 2048
      mask_ratio: 0.25
      norm_pix_loss: True
  pool_model:
      dim: 768
      int_dim: 512
      num_heads: 2
  num_classes: 31